version: '3'
services:
  app:
    image: cinemaspremierebackend
    container_name: cinemaspremierebackend
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        # The URL_BASE used when generating the types used by the Prisma ORM is slightly
        # different than the one used to call the GraphQL Server. That's why URL_BASE is here twice
        URL_BASE: ${GENERATE_URL_BASE}
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      URL_BASE: ${URL_BASE}
      NODE_ENV: ${NODE_ENV}
      SECRET: ${SECRET}
    ports:
      - 4000:4000
