name: CinemasPremiereCD
on:
  push:
    branches:
      - 'master'
jobs:
  prisma_deploy:
    name: Run Prisma Deploy
    uses: actions/setup-node@v2
    with:
      node-version: '14'
      cache: 'npm'
    env:
      PRISMA_MANAGEMENT_API_SECRET: ${{ secrets.PRISMA_MANAGEMENT_API_SECRET }}
    run: npm install @prisma/cli
    run: prisma deploy
