name: CinemasPremiereCD
on:
  push
  # push:
  # branches:
  #   - 'main'
jobs:
  prisma_deploy:
    name: Run Prisma Deploy
    runs-on: ubuntu-latest
    env:
      PRISMA_MANAGEMENT_API_SECRET: ${{ secrets.PRISMA_MANAGEMENT_API_SECRET }}
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Prisma CLI
        run: npm install -g prisma@1.34.10
      - name: Deploy to Prisma Cloud
        run: prisma deploy
