name: CinemasPremiereCD
on:
  push:
    branches:
      - 'main'
      - 'dev'
env:
  PRISMA_MANAGEMENT_API_SECRET: ${{ secrets.PRISMA_MANAGEMENT_API_SECRET }}
  URL_BASE: http://147.182.187.121:4466/taller2021/rguzman
jobs:
  prisma_deploy:
    name: Run Prisma Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set ENVRIONMENT value as production if push on main
        if: ${{github.ref == refs/heads/main}}
        env:
          ENVIRONMENT: production
      - name: Set ENVRIONMENT value as development if push on dev
        if: ${{github.ref == refs/heads/dev || github.ref == refs/heads/feature/InitialConfig}}
        env:
          ENVIRONMENT: development
      - name: Include repo contents in workspace
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Prisma CLI
        run: npm install -g prisma@1.34.10
      - name: Deploy to Prisma Cloud
        run: prisma deploy -p ${{ github.workspace }}/prisma/prisma.yml
